services:
  portfolio:
    image: ghcr.io/n0xum/p0rtfolio:latest
    pull_policy: always
    container_name: portfolio
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: nginx-proxy-manager_proxy
